apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: dex-ca-issuer
  namespace: tanzu-system-auth
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dex-cert
  namespace: tanzu-system-auth
spec:
  # Secret names are always required.
  secretName: dex-cert-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - vmware
  commonName: tkg-dex
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  # At least one of a DNS Name, USI SAN, or IP address is required.
  dnsNames:
  - tkg-dex
  ipAddresses:
    - <MGMT_CLUSTER_IP1>
    - <MGMT_CLUSTER_IP2>
  # Issuer references are always required.
  issuerRef:
    name: dex-ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io